### ISSUE TITLE
scheme entry

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/snow_blog#10]
### Tasks
- [ ] Create Parsers for the Grammar
- [ ] Calculator Logic
- [ ] Smart logic with bindings
- [ ] Record Data
    - Speed
    - Simplicity
- [ ] Blog Post reviewing Scheme
