### ISSUE TITLE
sxeme post 1

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/snow_blog#11]
### Tasks
- [ ] Describe problems facing
- [ ] Describe main focus
- [ ] Describe time table
- [ ] Describe main sources
